version: '{build}'

environment:
  TERM: dumb
  matrix:
    - JAVA_HOME: C:\Program Files (x86)\Java\jdk1.8.0
      PLATFORM: win32
    - JAVA_HOME: C:\Program Files\Java\jdk1.8.0
      PLATFORM: win64
install:
  - set PATH=%JAVA_HOME%\bin;%PATH%
  - echo %PATH%
  - gradlew.bat clean
  - set JAVA_OPTS=-XX:MaxPermSize=1024m -Xmx1512m -Dfile.encoding=UTF-8
  - set JAVA_TOOL_OPTIONS=-Dfile.encoding=UTF-8
  - choco install -y InnoSetup
  - set PATH="C:\\Program Files (x86)\\Inno Setup 5";%PATH%


build_script:
  - gradlew.bat -u -i clean assemble

artifacts:
  - path: build\distributions\*.exe
    name: setup-zest-writer-for-windows

on_failure:
  - echo Somebody setup us the bomb

deploy:
  - provider: BinTray
    on:
      appveyor_repo_tag: true
    username: firm2
    version: $(APPVEYOR_REPO_TAG_NAME)
    api_key:
      secure: vAEXLy1B2dK6n9JB/VQFG9M7jEV6T4wpjqG7PVcRRUafWQ1dQ0YKGKLg/p07sU5y
    subject: zest-writer
    repo: $(PLATFORM)
    package: zest-writer
    publish: true
    override: false
    explode: false
